version: "3"
services:
  react-app:
    stdin_open: true #Mantém o container rodando. Necessário por conta de um bug no react-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: . #A pasta onde nossos arquivos estão localizados
      dockerfile: Dockerfile.dev #O arquivo que queremos executar
    restart: always
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app #Toda vez que atualizar o '.', irá refletir em '/app'
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]